export const STORIES = '/'
export const STORY = '/story/:id'
export const USER = '/user/:id'
export const ACCOUNT = '/account'
export const CREATE_STORY = '/create-story'
export const ADMIN = '/admin'
export const SIGN_IN = '/sign-in'
export const SIGN_UP = '/sign-up'
