// profile
export const FETCH_PROFILE_PENDING = 'FETCH_PROFILE_PENDING'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'
export const fetchProfileTypes = {
  pending: FETCH_PROFILE_PENDING,
  success: FETCH_PROFILE_SUCCESS,
  failure: FETCH_PROFILE_FAILURE,
}
